version: '3.8'

services:
  # FastAPI Heart Disease Prediction Service
  heart-disease-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heart_disease_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./api:/app/api:ro
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
